name: catcher
description: Plugin for error catching. Allows handling errors when they're not catched by developer. Plugin provides multiple handlers for errors.
version: 0.6.5
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.0.3
  device_info_plus: ^1.0.0
  device_info_plus_platform_interface: ^1.0.1
  package_info_plus: ^1.0.0
  mailer: ^5.0.0
  dio: ^4.0.0
  flutter_mailer: ^1.0.1
  logging: ^1.0.1
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^2.0.20

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
